version: '3.1'

services:

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - ${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ${DB_VOL}:/data/db
